--<<<<<<< HEAD
--﻿--CREATE TABLE [dbo].[CustomerLocation]
----(
----	[CustomerId] INT NOT NULL PRIMARY KEY,
----	[LocationId] INT NOT NULL PRIMARY KEY
----)
--=======
--﻿CREATE TABLE [dbo].[CustomerLocation]
--(
--	[CustomerId] INT NOT NULL,
--	[LocationId] INT NOT NULL, 
--    CONSTRAINT [PK_CustomerLocation] PRIMARY KEY ([LocationId], [CustomerId])
--)
-->>>>>>> a49caaeb74d7394957eb7027d2b0a3c8751a46ef
