CREATE TABLE [dbo].[Customer]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(120) NOT NULL, 
    [IdentityCode] VARCHAR(20) NULL, -- Business License (GPKD), Identity Card (CMND), Citizenship Card (CCCD), Passport (Hộ chiếu)
    [Type] TINYINT NULL, 
    [Phone] VARCHAR(12) NOT NULL, 
    [Email] VARCHAR(254) NULL, 
    [Address] NVARCHAR(128) NOT NULL, 
    [PaymentMethodId] INT NOT NULL, 
    [CustomerGroupId] INT NOT NULL, 
    --[MembershipClassId] INT NULL, 
    [IsInvoice] BIT NOT NULL DEFAULT 0, 
    [Note] NVARCHAR(100) NULL, 
    [Status] TINYINT NULL, 
    [IsDefault] BIT NOT NULL DEFAULT 0,   -- 0 Unavailable (Ngừng hoạt động) , 1 Available (Đang hoạt động))
    [GenderId] INT NULL, 
    [DoB] DATE NULL, 
    [Tag] VARCHAR(120) NULL, 
    [CreateDate] DATE NULL, 
    CreditLimit NUMERIC(16,2),
    PaymentTerm NUMERIC(5,0),
    StockId INT,
    Representative nvarchar(32) null,
    RepPhone varchar(12) null,
    Operator nvarchar(32) null,
    OpePhone varchar(12) null,
    Map varchar(1000) null,
    UserId BIGINT,
    --CONSTRAINT [FK_Customer_UserId] FOREIGN KEY ([UserId]) REFERENCES [User]([Id]), 
    CONSTRAINT [FK_Customer_StockId] FOREIGN KEY ([StockId]) REFERENCES [Stock]([Id]), 
    CONSTRAINT [FK_Customer_PaymentMethod] FOREIGN KEY ([PaymentMethodId]) REFERENCES [PaymentMethod]([Id]), 
    CONSTRAINT [FK_Customer_CustomerGroup] FOREIGN KEY ([CustomerGroupId]) REFERENCES [CustomerGroup]([Id]), 
    --CONSTRAINT [FK_Customer_MembershipClass] FOREIGN KEY ([MembershipClassId]) REFERENCES [MembershipClass]([Id]), 
    CONSTRAINT [FK_Customer_Gender] FOREIGN KEY ([GenderId]) REFERENCES [Gender]([Id]))
